# Creates the image to run the server locally

FROM node:10.16.0

# Create app directory
WORKDIR /usr/app

ENV CRON_INTERVAL_MS 5000
ENV PORT 8080
ENV DATABASE_URL postgresql://gio:testing123@db:5432/my_db


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./
COPY bootstrap-server-dev.sh ./
COPY src/ ./src
COPY schema.prisma ./

RUN npm install && \
    npm run build && \
    npx prisma generate

CMD [ "/usr/app/bootstrap-server-dev.sh" ]

