# Creates the image to run the server locally

FROM node:14.15-stretch

# Create app directory
WORKDIR /usr/app



# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./
COPY bootstrap-server-dev.sh ./
COPY src/ ./src
COPY schema.prisma ./

RUN npm install && \
    npm run build && \
    npx prisma generate

CMD [ "/usr/app/bootstrap-server-dev.sh" ]

