FROM node:10.16.0

# Create app directory
WORKDIR /usr/app

ENV DATABASE_HOST db
ENV DATABASE_USER gio
ENV DATABASE_PASSWORD testing123
ENV DATABASE_NAME my_db

# every minute locally
ENV CRON_INTERVAL_MS 60000

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY tsconfig.json ./
COPY bootstrap-server-dev.sh ./
COPY src/ ./src
COPY knexfile.js ./

RUN npm install && npm run build

EXPOSE 8080

CMD [ "/usr/app/bootstrap-server-dev.sh" ]
